# Makefile with basic concepts
 
# Define compiler and options
CC=clang
CFLAGS= -Wall -Wextra -std=c99 -O2
 
# avoid calling make without option
# ONLY FOR THIS EXERCICE
all:
	@echo "*** NO RULES ***"
	@false
 
clean::
	rm -f *~ *.o
 
# END (do not delete)
